server:
  port:8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://localhost:8081
          predicates:
            - path=/auth/**
          filter:
            - stripPrefix=1

        - id : patient-service
          uri: http://localhost:4000
          predicates:
            - path=/patient/**
          filter:
            - stripPrefix=1

