app:
  api-key: ${apikey}
server:
  port:8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - ApiKeyValidation

        - id: patient-service-foradmin
          uri: http://localhost:4000
          predicates:
            - Path=/patients/admin/**
          filters:
            - name: JwtValidation
              args:
                allowedRoles: "ADMIN"

        - id : patient-service-forpatients
          uri: http://localhost:4000
          predicates:
            - Path=/patients/**
          filters:
            - name: JwtValidation
              args:
                allowedRoles: "USER"



